config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins

  resources :contacts, only: [:new, :create]
  authenticate :admin do
    resources :blog_posts, only: [:new, :create, :edit, :update, :destroy]
    resources :projects, only: [:new, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :edit, :update, :destroy, :show]
  end
    resources :blog_posts, only: [:index, :show]
  resources :projects, only: [:index,:show]

  root 'static#home'

  get 'static/about'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    #@blog_posts = BlogPost.all
    @blog_posts = BlogPost.all.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :subtitle, :content)
    end
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :destroy]
  # GET /contacts
  # GET /contacts.json
  def index
    #@contacts = BlogPost.all
    @contacts = Contact.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contact message was successfully sent.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :subtitle, :content)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (title)
		title + " | Devin Lee"
	end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :content %><br>
    <%= f.cktext_area :content, :class => "form-control", :rows=>"8" %>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= f.button :Create, :class => "form-control btn btn-success "%>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= link_to 'Back', blog_posts_path, {class: 'form-control btn btn-primary'} %>
  </div>
<% end %>

app/views/blog_posts/index.html.erb
<% provide(:title, "Blog") 
provide(:header_title, "Blog")
provide(:header_subtitle, "My thoughts, rants, and discoveries.")
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <hr>
    <% @blog_posts.each do |blog_post| %>
    <div class="post-preview">
      <%= link_to (blog_post) do %>
      <h2 class="post-title">
        <%= blog_post.title %>
      </h2>
      <h3 class="post-subtitle">
        <%= blog_post.subtitle%>
      </h3>
      <p class="post-meta">Posted on <%= blog_post.created_at.strftime('%m/%d/%Y')%></p>
      <hr>
      <% end%>
    </div>
    <% end %>
    <%= will_paginate @blog_posts, :page_links => false%>

    <% if admin_signed_in? %>
    <!-- Pager -->
    <ul class="pager">
      <li class="next">
        <%= link_to 'New Blog post', new_blog_post_path %>
      </li>
      
    </ul>
    
    <% end%>
  </div>

</div>

app/views/blog_posts/show.html.erb
<% provide(:title, @blog_post.title) 
provide(:header_title, @blog_post.title)
provide(:header_subtitle, @blog_post.subtitle)
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <p>
      <%= raw@blog_post.content %>
    </p>
    <% if admin_signed_in? %>
    <%= link_to 'Delete', @blog_post, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
    <%= link_to 'Back', blog_posts_path %>
    <% end %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :email %><br>
    <%= f.email_field :email, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :phone %><br>
    <%= f.phone_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :message %><br>
    <%= f.cktext_area :message, :class => "form-control", :rows=>"8" %>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= f.button :Create, :class => "form-control btn btn-success "%>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= link_to 'Back', "history.back()", {class: 'form-control btn btn-primary'} %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<% provide(:title, "Contacts") 
provide(:header_title, "Contacts")
provide(:header_subtitle, "My inbox.")
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <hr>
    <% @contacts.each do |contact| %>
    <div class="post-preview">
      <%= link_to (contact) do %>
      <h2 class="post-title">
        <%= contact.name %>
      </h2>
      <h3 class="post-subtitle">
        <%= contact.email%>
      </h3>
      <p class="post-meta">Posted on <%= contact.created_at.strftime('%m/%d/%Y')%></p>
      <hr>
      <% end%>
    </div>
    <% end %>
    <%= will_paginate @contacts, :page_links => false%>

  </div>

</div>

app/views/contacts/new.html.erb
<% provide(:title, "Contact") 
provide(:header_title, "Contact Me")
provide(:header_subtitle, "If you were kind enough to visit my page, I'd like to get to know you! Fill out the form below to send me a message and I will try to get back to you within a few days.")
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <%= render 'form' %>

  </div>
</div>

app/views/contacts/show.html.erb
<% provide(:title, Contact) 
provide(:header_title, @contact.name)
provide(:header_subtitle, @contact.email)
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <p>Phone number: <%= @contact.phone%></p>
    <p>
      <%= raw@contact.message %>
    </p>
    <% if admin_signed_in? %>
    <%= link_to 'Delete', @contact, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Edit', edit_contact_path(@contact) %> |
    <%= link_to 'Back', contacts_path %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer col-md-10 col-md-offset-1">
  <small>
    Devin Lee &copy; 2015
  </small>
  <nav>
    <ul>
      <% if admin_signed_in? %>
      <li class="nav-item"><small><%= link_to("Inbox", contacts_path)%> | <%= link_to("Sign out",destroy_admin_session_path, :method=>:delete) %></small></li>
      <% end %>
      <li><small><a href="https://www.linkedin.com/pub/devin-lee/55/347/a05">

        <img src="https://static.licdn.com/scds/common/u/img/webpromo/btn_profile_greytxt_80x15.png" width="80" height="15" border="0" alt="View Devin Lee's profile on LinkedIn">
        
        </a> | <%= link_to "Contact me", new_contact_path %></small></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand navbar-brand-centered" href="/">Devin Lee</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsable-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapsable-navbar">
      <ul class="nav navbar-nav navbar-nav-to-left">
        <li class="nav-item"><%= link_to "About",static_about_path %></li>
        <li class="nav-item"><%= link_to "Blog",blog_posts_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-nav-to-right">
        <li class="nav-item"><%= link_to "Projects",projects_path %></li>
        <li class="nav-item"><a href="https://instagram.com/exia909/">Photos</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1><%= yield(:header_title) %></h1>
          <hr class="small">
          <span class="subheading"><%= yield(:header_subtitle) %></span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initialy-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="edge">
  <meta name="author" content="Devin Lee">
  <meta name="theme-color" content="#0066CC">
	<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "custom", :media => "all", 'data-turbolinks-track'=>true%>
  <%= stylesheet_link_tag "application", params[:controller], :media => "all", 'data-turbolinks-track'=>true%>
	<%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>

  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
 <%= render 'layouts/header'%>
 <div class="container">
  <%= yield %>
  <%= render 'layouts/footer'%>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, :class => "form-control" %>
  </div>
  <div class="form-group col-xs-12 floating-label-form-group controls">
    <%= f.label :content %><br>
    <%= f.cktext_area :content, :class => "form-control", :rows=>"8" %>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= f.button :Create, :class => "form-control btn btn-success "%>
  </div>
  <div class="form-group col-md-2 col-sm-3 floating-label-form-group controls pull-right">
    <%= link_to 'Back', blog_posts_path, {class: 'form-control btn btn-primary'} %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/projects/index.html.erb
<% provide(:title, "Projects") 
provide(:header_title, "Projects")
provide(:header_subtitle, "Creating tangible and intangible traces that I walked on this fine planet!")
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <hr>
    <% @projects.each do |project| %>
    <div class="post-preview">
      <%= link_to (project) do %>
      <h2 class="post-title">
        <%= project.title %>
      </h2>
      <h3 class="post-subtitle">
        <%= project.subtitle%>
      </h3>
      <p class="post-meta">Posted on <%= project.created_at.strftime('%m/%d/%Y')%></p>
      <hr>
      <% end%>
    </div>
    <% end %>
    <%= will_paginate @projects, :page_links => false%>
    

    <% if admin_signed_in? %>
    <!-- Pager -->
    <ul class="pager">
      <li class="next">
        <%= link_to 'New Project Post', new_project_path %>
      </li>
      
    </ul>
    
    <% end%>
  </div>

</div>

app/views/projects/new.html.erb
<% provide(:title, "New Project") 
provide(:header_title, "New Project")
provide(:header_subtitle, "Write down everything about the project.")
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <h1>New Project</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.title) 
provide(:header_title, @project.title)
provide(:header_subtitle, @project.subtitle)
%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <p>
      <%= raw@project.content %>
    </p>
    <% if admin_signed_in? %>
    <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
    <% end %>
  </div>
</div>